site_name: Leading Edge DC-3 v2
site_url: https://airfightergr.github.io/les_dc3_docs/

nav:
  - index.md
  - Aircraft Types:
      - Classic Aircraft: acf_classic.md
      - Modern Aircraft: acf_modern.md


theme: readthedocs