site_name: Leading Edge Simulations DC-3 v2
site_url: https://airfightergr.github.io/les_dc3_docs/

nav:
  - Welcome:
    - Overview: index.md
    - Aircraft Characteristics: characteristics.md
    - User Interface: gui.md
    - Liveries Concept: liveries.md
    - Controls Setup: commands.md
    - Support: support.md
  - 'Select Aircraft':
    - DC-3 Classic:
        - Introduction: docs/classic/classic.md
        - Pilot's Panel: docs/classic/plt_panel.md
        - Copilot's Panel: docs/classic/cplt_panel.md
        - Center Panel: docs/classic/center_panel.md
        - Pedestal: docs/classic/pedestal.md
        - Radios: docs/classic/radios.md
        - Automatic Pilot: docs/classic/autopilot.md
    - DC-3 Modern:
        - Introduction: docs/modern/modern.md
        - Pilot's Panel: docs/modern/pilot.md
        - Copilot's Panel: docs/modern/copilot.md
        - Center Panel: docs/modern/center_panel.md
        - Radios & Avionics: docs/modern/avionics.md
    - Common Systems:
        - Overhead: docs/common/overhead.md
        - Hydraulics: docs/common/hydraulics.md
        - Other Systems: docs/common/other.md
        - Engines Start: docs/common/engines_start.md


theme:
    name: readthedocs

    #mkdocs, readthedocs, bootstrap,
  #            cerulean, cosmo, cyborg, darkly, flatly, journal, litera, lumen,
  #            lux, materia, minty, pulse, sandstone, simplex, slate, solar,
  #            spacelab, superhero, united, yeti

markdown_extensions:
  - admonition
  - tables

plugins:
  - mkdocs-video
